feat: add `DNS_PROFILE` environment variable for changing the DNS profile
https://blog.cloudflare.com/introducing-1-1-1-1-for-families

diff --git a/internal/wgcf b/internal/wgcf
--- a/internal/wgcf
+++ b/internal/wgcf
@@ -62,6 +62,25 @@ update_wgcf_config() {
     sed -i -e "s/Endpoint =.*/Endpoint = $WGCF_ENDPOINT/g" wgcf-profile.conf
   fi
 
+  # DNS Profile
+  if [ -n "$DNS_PROFILE" ]; then
+    local _DNS_PROFILE="$(uppercase "$DNS_PROFILE")"
+    log "notice" "Applying DNS Profile: $DNS_PROFILE"
+    declare -A DNS_PROFILES
+    DNS_PROFILES=(
+      ["DEFAULT"]="1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, 2606:4700:4700::1001"
+      ["MALWARE-ONLY"]="1.1.1.2, 1.0.0.2, 2606:4700:4700::1112, 2606:4700:4700::1112"
+      ["MALWARE-AND-ADULT"]="1.1.1.3, 1.0.0.3, 2606:4700:4700::1113, 2606:4700:4700::1003"
+    )
+
+    if [[ -v DNS_PROFILES[$_DNS_PROFILE] ]]; then
+      sed -i -e "s/DNS =.*/DNS = ${DNS_PROFILES[$_DNS_PROFILE]}/g" wgcf-profile.conf
+    else
+      log "error" "Invalid DNS Profile: $_DNS_PROFILE"
+      exit 1
+    fi
+  fi
+
   cp wgcf-profile.conf "$DIST_DIR/wgcf-profile.conf"
   popd &> /dev/null || exit 1
   rm -fr "$TEMP_DIR"
